[project]
docs_dir = "."
nav = [
  { "Home" = "index.md" },
  { "Reference" = [
    { "Layer Stack" = "layer_stack.md" },
    { "Cells Si220" = "cells_si220.md" },
    { "Cells Si340" = "cells_si340.md" },
    { "Cells Si500" = "cells_si500.md" },
    { "Cells SiN200" = "cells_sin200.md" },
    { "Cells SiN300" = "cells_sin300.md" },
    { "Cells Suspended Si" = "cells_si_sus.md" },
    { "Cells Ge-on-Si" = "cells_ge_on_si.md" },
    { "Changelog" = "changelog.md" }
  ] }
]
site_dir = "_build/html"
site_name = "CornerStone PDK"
site_url = "https://gdsfactory.github.io/cspdk"

[project.plugins.autorefs]

[project.plugins.mkdocstrings]

[project.plugins.mkdocstrings.handlers.python]

[project.plugins.mkdocstrings.handlers.python.options]
docstring_style = "google"
show_root_toc_entry = false
show_source = false

[project.plugins.search]

[project.theme]
logo = "logo.png"
name = "material"
